# Generated by Django 5.1.4 on 2024-12-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallno', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('coloumns', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Usertype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.branch')),
                ('Sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.semester')),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.branch')),
                ('Semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.login')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Seating_Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Exam_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Seat_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('Exam_time', models.TimeField(blank=True, max_length=100, null=True)),
                ('Reg_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom_NO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.classroom')),
                ('Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Exam_Date', models.DateField(blank=True, max_length=100, null=True)),
                ('Exam_Time', models.TimeField(blank=True, max_length=100, null=True)),
                ('NO_of_students', models.CharField(blank=True, max_length=100, null=True)),
                ('Duration_hours', models.IntegerField(blank=True, null=True)),
                ('Exam_Subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Seating_Arrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.examdetail')),
                ('Exam_Hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.classroom')),
                ('Teachers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.login')),
            ],
        ),
    ]
