# Generated by Django 5.1.4 on 2024-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='coloumns',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
