# Generated by Django 5.1.4 on 2024-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0002_alter_classroom_capacity_alter_classroom_coloumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
