# Generated by Django 5.1.4 on 2024-12-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0003_branch_branch_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='branchname',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='Semester_Name',
            new_name='semestername',
        ),
    ]
