# Generated by Django 5.1.4 on 2024-12-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0005_rename_branch_subject_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_Code',
            new_name='subjectcode',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_Name',
            new_name='subjectname',
        ),
    ]
