# Generated by Django 5.1.4 on 2024-12-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0006_rename_subject_code_subject_subjectcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('no_of_students', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_hours', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_seating_arrangement',
            name='Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.examdetails'),
        ),
        migrations.DeleteModel(
            name='ExamDetail',
        ),
    ]
