# Generated by Django 5.1.4 on 2024-12-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0007_examdetails_alter_teacher_seating_arrangement_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(blank=True, max_length=30, null=True)),
                ('auto_generate_registerno', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.branch')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.semester')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='Arrangementapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
