# Generated by Django 5.1.4 on 2024-12-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0008_studentprofile_delete_student_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='coloumns',
            new_name='columns',
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='hallno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
