# Generated by Django 5.1.4 on 2024-12-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0009_rename_coloumns_classroom_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
