# Generated by Django 5.1.4 on 2024-12-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0011_teacherseatingarrangement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_profile',
            old_name='Staff_id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='staff_profile',
            old_name='Subject',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='staff_profile',
            old_name='User_id',
            new_name='user',
        ),
    ]
