# Generated by Django 5.1.4 on 2024-12-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0012_rename_staff_id_staff_profile_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
