# Generated by Django 5.1.4 on 2024-12-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0014_login_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='is_active',
            field=models.BooleanField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
