# Generated by Django 5.1.4 on 2025-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0016_examnotification_alter_studentprofile_user_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaints',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
