# Generated by Django 5.1.4 on 2025-01-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0017_complaint_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Date',
            field=models.DateField(auto_now_add=True, max_length=100, null=True),
        ),
    ]
