# Generated by Django 5.1.4 on 2025-01-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0020_rename_classroom_no_seating_arrangement_classroom_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerno', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='Images/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Arrangementapp.login')),
            ],
        ),
    ]
