# Generated by Django 5.1.4 on 2025-01-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0021_malpractice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examnotification',
            name='Exam_Date',
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='Exam_Name',
        ),
        migrations.RemoveField(
            model_name='examnotification',
            name='exam_time',
        ),
        migrations.AddField(
            model_name='examnotification',
            name='notification_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
