# Generated by Django 5.1.4 on 2025-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangementapp', '0023_remove_complaint_reply_complaint_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='examnotification',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
